# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

workspace 'GistApp.xcworkspace'

target 'GistApp' do
  use_frameworks!

  target 'GistAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'GistList' do
  use_frameworks!

  project './Libs/GistList/GistList.xcodeproj'

  # Pods for GistList
  pod 'SnapKit'
end
