platform :ios, '16.0'

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
  end
 end
end

workspace 'GistApp.xcworkspace'

target 'GistApp' do
  use_frameworks!

  pod 'SnapKit', '~> 5.0'

  target 'GistAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'GistList' do
  use_frameworks!

  project './Libs/GistList/GistList.xcodeproj'

  pod 'SnapKit', '~> 5.0'
end
