name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Ajuste para a versão do Ruby que você precisa
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install cocoapods
        cd GistApp # Acesse o diretório correto onde o Podfile está localizado
        pod install

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1' # Ajuste para a versão do Xcode que você precisa

    - name: Build
      run: xcodebuild -workspace GistApp.xcworkspace -scheme GistApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest' build
      working-directory: ./GistApp # Defina o diretório de trabalho correto

    - name: Run tests
      run: xcodebuild -workspace GistApp.xcworkspace -scheme GistApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest' test
      working-directory: ./GistApp # Defina o diretório de trabalho correto
